# Generated by Django 5.0.7 on 2024-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abt_Presonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_heading1', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pics')),
                ('h1_desc', models.TextField()),
                ('heading21', models.CharField(max_length=255)),
                ('heading21_desc', models.TextField()),
                ('heading22', models.CharField(max_length=255)),
                ('heading22_desc', models.TextField()),
                ('heading23', models.CharField(max_length=255)),
                ('heading23_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='What_we_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
