# Generated by Django 5.0.7 on 2024-07-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0004_blog_list_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_list',
        ),
        migrations.AddField(
            model_name='blog_lists',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menan.category'),
        ),
    ]
