# Generated by Django 5.0.7 on 2024-07-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0005_blog_lists_category_delete_blog_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_lists',
        ),
    ]
