# Generated by Django 5.0.7 on 2024-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0007_contact_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_url', models.URLField(help_text='Enter the Google Maps embed URL here.')),
            ],
            options={
                'verbose_name': 'Map Setting',
                'verbose_name_plural': 'Map Settings',
            },
        ),
    ]
