# Generated by Django 5.0.7 on 2024-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0008_mapsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
