# Generated by Django 5.0.7 on 2024-09-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menan', '0010_appointments_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
