# Generated by Django 5.0.7 on 2024-07-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menan', '0006_delete_blog_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menan.category')),
            ],
        ),
    ]
