# Generated by Django 5.0.7 on 2024-09-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('menan', '0011_delete_dentist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menan.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
