# Generated by Django 5.0.6 on 2024-06-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
