# Generated by Django 5.0.7 on 2024-07-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_pricing_prititle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('year_of_exp', models.IntegerField()),
                ('year_of_exp_txt', models.CharField(max_length=255)),
                ('qua_dent', models.IntegerField()),
                ('qua_dent_txt', models.CharField(max_length=255)),
                ('customer', models.IntegerField()),
                ('customer_txt', models.CharField(max_length=255)),
                ('ppy', models.IntegerField()),
                ('ppy_txt', models.CharField(max_length=255)),
            ],
        ),
    ]
