# Generated by Django 5.0.7 on 2024-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('prof', models.CharField(max_length=100)),
                ('X', models.URLField(blank=True, null=True)),
                ('fb', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
